# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import image_pb2 as image__pb2


class CameraControllerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get_current_image = channel.unary_unary(
        '/smartbox_msgs.CameraController/get_current_image',
        request_serializer=image__pb2.CameraImageRequest.SerializeToString,
        response_deserializer=image__pb2.CameraImageResponse.FromString,
        )


class CameraControllerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def get_current_image(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CameraControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get_current_image': grpc.unary_unary_rpc_method_handler(
          servicer.get_current_image,
          request_deserializer=image__pb2.CameraImageRequest.FromString,
          response_serializer=image__pb2.CameraImageResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'smartbox_msgs.CameraController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
