# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image.proto',
  package='smartbox_msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x0bimage.proto\x12\rsmartbox_msgs\"%\n\x12\x43\x61meraImageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"B\n\x13\x43\x61meraImageResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r2p\n\x10\x43\x61meraController\x12\\\n\x11get_current_image\x12!.smartbox_msgs.CameraImageRequest\x1a\".smartbox_msgs.CameraImageResponse\"\x00\x62\x06proto3')
)




_CAMERAIMAGEREQUEST = _descriptor.Descriptor(
  name='CameraImageRequest',
  full_name='smartbox_msgs.CameraImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='smartbox_msgs.CameraImageRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=67,
)


_CAMERAIMAGERESPONSE = _descriptor.Descriptor(
  name='CameraImageResponse',
  full_name='smartbox_msgs.CameraImageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='smartbox_msgs.CameraImageResponse.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='smartbox_msgs.CameraImageResponse.width', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='smartbox_msgs.CameraImageResponse.height', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['CameraImageRequest'] = _CAMERAIMAGEREQUEST
DESCRIPTOR.message_types_by_name['CameraImageResponse'] = _CAMERAIMAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraImageRequest = _reflection.GeneratedProtocolMessageType('CameraImageRequest', (_message.Message,), dict(
  DESCRIPTOR = _CAMERAIMAGEREQUEST,
  __module__ = 'image_pb2'
  # @@protoc_insertion_point(class_scope:smartbox_msgs.CameraImageRequest)
  ))
_sym_db.RegisterMessage(CameraImageRequest)

CameraImageResponse = _reflection.GeneratedProtocolMessageType('CameraImageResponse', (_message.Message,), dict(
  DESCRIPTOR = _CAMERAIMAGERESPONSE,
  __module__ = 'image_pb2'
  # @@protoc_insertion_point(class_scope:smartbox_msgs.CameraImageResponse)
  ))
_sym_db.RegisterMessage(CameraImageResponse)



_CAMERACONTROLLER = _descriptor.ServiceDescriptor(
  name='CameraController',
  full_name='smartbox_msgs.CameraController',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=137,
  serialized_end=249,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_current_image',
    full_name='smartbox_msgs.CameraController.get_current_image',
    index=0,
    containing_service=None,
    input_type=_CAMERAIMAGEREQUEST,
    output_type=_CAMERAIMAGERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CAMERACONTROLLER)

DESCRIPTOR.services_by_name['CameraController'] = _CAMERACONTROLLER

# @@protoc_insertion_point(module_scope)
