# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lights.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lights.proto',
  package='smartbox_msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x0clights.proto\x12\rsmartbox_msgs\"t\n\x0cLightRequest\x12\x37\n\x05light\x18\x01 \x01(\x0e\x32(.smartbox_msgs.LightRequest.LightSetting\"+\n\x0cLightSetting\x12\n\n\x06STATUS\x10\x00\x12\x06\n\x02ON\x10\x01\x12\x07\n\x03OFF\x10\x02\"i\n\rLightResponse\x12\x38\n\x06status\x18\x01 \x01(\x0e\x32(.smartbox_msgs.LightResponse.LightStatus\"\x1e\n\x0bLightStatus\x12\x06\n\x02ON\x10\x00\x12\x07\n\x03OFF\x10\x01\x32[\n\x0fLightController\x12H\n\tset_light\x12\x1b.smartbox_msgs.LightRequest\x1a\x1c.smartbox_msgs.LightResponse\"\x00\x62\x06proto3')
)



_LIGHTREQUEST_LIGHTSETTING = _descriptor.EnumDescriptor(
  name='LightSetting',
  full_name='smartbox_msgs.LightRequest.LightSetting',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OFF', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=104,
  serialized_end=147,
)
_sym_db.RegisterEnumDescriptor(_LIGHTREQUEST_LIGHTSETTING)

_LIGHTRESPONSE_LIGHTSTATUS = _descriptor.EnumDescriptor(
  name='LightStatus',
  full_name='smartbox_msgs.LightResponse.LightStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ON', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OFF', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=224,
  serialized_end=254,
)
_sym_db.RegisterEnumDescriptor(_LIGHTRESPONSE_LIGHTSTATUS)


_LIGHTREQUEST = _descriptor.Descriptor(
  name='LightRequest',
  full_name='smartbox_msgs.LightRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='light', full_name='smartbox_msgs.LightRequest.light', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LIGHTREQUEST_LIGHTSETTING,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=147,
)


_LIGHTRESPONSE = _descriptor.Descriptor(
  name='LightResponse',
  full_name='smartbox_msgs.LightResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='smartbox_msgs.LightResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LIGHTRESPONSE_LIGHTSTATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=254,
)

_LIGHTREQUEST.fields_by_name['light'].enum_type = _LIGHTREQUEST_LIGHTSETTING
_LIGHTREQUEST_LIGHTSETTING.containing_type = _LIGHTREQUEST
_LIGHTRESPONSE.fields_by_name['status'].enum_type = _LIGHTRESPONSE_LIGHTSTATUS
_LIGHTRESPONSE_LIGHTSTATUS.containing_type = _LIGHTRESPONSE
DESCRIPTOR.message_types_by_name['LightRequest'] = _LIGHTREQUEST
DESCRIPTOR.message_types_by_name['LightResponse'] = _LIGHTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LightRequest = _reflection.GeneratedProtocolMessageType('LightRequest', (_message.Message,), dict(
  DESCRIPTOR = _LIGHTREQUEST,
  __module__ = 'lights_pb2'
  # @@protoc_insertion_point(class_scope:smartbox_msgs.LightRequest)
  ))
_sym_db.RegisterMessage(LightRequest)

LightResponse = _reflection.GeneratedProtocolMessageType('LightResponse', (_message.Message,), dict(
  DESCRIPTOR = _LIGHTRESPONSE,
  __module__ = 'lights_pb2'
  # @@protoc_insertion_point(class_scope:smartbox_msgs.LightResponse)
  ))
_sym_db.RegisterMessage(LightResponse)



_LIGHTCONTROLLER = _descriptor.ServiceDescriptor(
  name='LightController',
  full_name='smartbox_msgs.LightController',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=256,
  serialized_end=347,
  methods=[
  _descriptor.MethodDescriptor(
    name='set_light',
    full_name='smartbox_msgs.LightController.set_light',
    index=0,
    containing_service=None,
    input_type=_LIGHTREQUEST,
    output_type=_LIGHTRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LIGHTCONTROLLER)

DESCRIPTOR.services_by_name['LightController'] = _LIGHTCONTROLLER

# @@protoc_insertion_point(module_scope)
