# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import temperature_pb2 as temperature__pb2


class TemperatureControllerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.panel_temperature = channel.unary_unary(
        '/smartbox_msgs.TemperatureController/panel_temperature',
        request_serializer=temperature__pb2.PanelTemperatureRequest.SerializeToString,
        response_deserializer=temperature__pb2.PanelTemperatureResponse.FromString,
        )


class TemperatureControllerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def panel_temperature(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TemperatureControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'panel_temperature': grpc.unary_unary_rpc_method_handler(
          servicer.panel_temperature,
          request_deserializer=temperature__pb2.PanelTemperatureRequest.FromString,
          response_serializer=temperature__pb2.PanelTemperatureResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'smartbox_msgs.TemperatureController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
