# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temperature.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='temperature.proto',
  package='smartbox_msgs',
  syntax='proto3',
  serialized_pb=_b('\n\x11temperature.proto\x12\rsmartbox_msgs\"4\n\x11TemperatureSensor\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x10\n\x08location\x18\x02 \x01(\t\"*\n\x17PanelTemperatureRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"M\n\x18PanelTemperatureResponse\x12\x31\n\x07sensors\x18\x01 \x03(\x0b\x32 .smartbox_msgs.TemperatureSensor2\x7f\n\x15TemperatureController\x12\x66\n\x11panel_temperature\x12&.smartbox_msgs.PanelTemperatureRequest\x1a\'.smartbox_msgs.PanelTemperatureResponse\"\x00\x62\x06proto3')
)




_TEMPERATURESENSOR = _descriptor.Descriptor(
  name='TemperatureSensor',
  full_name='smartbox_msgs.TemperatureSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='smartbox_msgs.TemperatureSensor.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='smartbox_msgs.TemperatureSensor.location', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=88,
)


_PANELTEMPERATUREREQUEST = _descriptor.Descriptor(
  name='PanelTemperatureRequest',
  full_name='smartbox_msgs.PanelTemperatureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='smartbox_msgs.PanelTemperatureRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=132,
)


_PANELTEMPERATURERESPONSE = _descriptor.Descriptor(
  name='PanelTemperatureResponse',
  full_name='smartbox_msgs.PanelTemperatureResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensors', full_name='smartbox_msgs.PanelTemperatureResponse.sensors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=211,
)

_PANELTEMPERATURERESPONSE.fields_by_name['sensors'].message_type = _TEMPERATURESENSOR
DESCRIPTOR.message_types_by_name['TemperatureSensor'] = _TEMPERATURESENSOR
DESCRIPTOR.message_types_by_name['PanelTemperatureRequest'] = _PANELTEMPERATUREREQUEST
DESCRIPTOR.message_types_by_name['PanelTemperatureResponse'] = _PANELTEMPERATURERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TemperatureSensor = _reflection.GeneratedProtocolMessageType('TemperatureSensor', (_message.Message,), dict(
  DESCRIPTOR = _TEMPERATURESENSOR,
  __module__ = 'temperature_pb2'
  # @@protoc_insertion_point(class_scope:smartbox_msgs.TemperatureSensor)
  ))
_sym_db.RegisterMessage(TemperatureSensor)

PanelTemperatureRequest = _reflection.GeneratedProtocolMessageType('PanelTemperatureRequest', (_message.Message,), dict(
  DESCRIPTOR = _PANELTEMPERATUREREQUEST,
  __module__ = 'temperature_pb2'
  # @@protoc_insertion_point(class_scope:smartbox_msgs.PanelTemperatureRequest)
  ))
_sym_db.RegisterMessage(PanelTemperatureRequest)

PanelTemperatureResponse = _reflection.GeneratedProtocolMessageType('PanelTemperatureResponse', (_message.Message,), dict(
  DESCRIPTOR = _PANELTEMPERATURERESPONSE,
  __module__ = 'temperature_pb2'
  # @@protoc_insertion_point(class_scope:smartbox_msgs.PanelTemperatureResponse)
  ))
_sym_db.RegisterMessage(PanelTemperatureResponse)



_TEMPERATURECONTROLLER = _descriptor.ServiceDescriptor(
  name='TemperatureController',
  full_name='smartbox_msgs.TemperatureController',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=213,
  serialized_end=340,
  methods=[
  _descriptor.MethodDescriptor(
    name='panel_temperature',
    full_name='smartbox_msgs.TemperatureController.panel_temperature',
    index=0,
    containing_service=None,
    input_type=_PANELTEMPERATUREREQUEST,
    output_type=_PANELTEMPERATURERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEMPERATURECONTROLLER)

DESCRIPTOR.services_by_name['TemperatureController'] = _TEMPERATURECONTROLLER

# @@protoc_insertion_point(module_scope)
