# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tracker_pb2 as tracker__pb2


class TrackerControllerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get_tracker_status = channel.unary_unary(
        '/smartbox.TrackerController/get_tracker_status',
        request_serializer=tracker__pb2.TrackerSystemStatusRequest.SerializeToString,
        response_deserializer=tracker__pb2.TrackerSystemStatusResponse.FromString,
        )
    self.request_control = channel.unary_unary(
        '/smartbox.TrackerController/request_control',
        request_serializer=tracker__pb2.RequestControlRequest.SerializeToString,
        response_deserializer=tracker__pb2.RequestControlResponse.FromString,
        )
    self.relinquish_control = channel.unary_unary(
        '/smartbox.TrackerController/relinquish_control',
        request_serializer=tracker__pb2.RelinquishControlRequest.SerializeToString,
        response_deserializer=tracker__pb2.RelinquishControlResponse.FromString,
        )
    self.move_panel = channel.unary_unary(
        '/smartbox.TrackerController/move_panel',
        request_serializer=tracker__pb2.MoveRequest.SerializeToString,
        response_deserializer=tracker__pb2.MoveResponse.FromString,
        )
    self.stop = channel.unary_unary(
        '/smartbox.TrackerController/stop',
        request_serializer=tracker__pb2.StopRequest.SerializeToString,
        response_deserializer=tracker__pb2.StopResponse.FromString,
        )
    self.stow = channel.unary_unary(
        '/smartbox.TrackerController/stow',
        request_serializer=tracker__pb2.StowRequest.SerializeToString,
        response_deserializer=tracker__pb2.StowResponse.FromString,
        )


class TrackerControllerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def get_tracker_status(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def request_control(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def relinquish_control(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def move_panel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TrackerControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get_tracker_status': grpc.unary_unary_rpc_method_handler(
          servicer.get_tracker_status,
          request_deserializer=tracker__pb2.TrackerSystemStatusRequest.FromString,
          response_serializer=tracker__pb2.TrackerSystemStatusResponse.SerializeToString,
      ),
      'request_control': grpc.unary_unary_rpc_method_handler(
          servicer.request_control,
          request_deserializer=tracker__pb2.RequestControlRequest.FromString,
          response_serializer=tracker__pb2.RequestControlResponse.SerializeToString,
      ),
      'relinquish_control': grpc.unary_unary_rpc_method_handler(
          servicer.relinquish_control,
          request_deserializer=tracker__pb2.RelinquishControlRequest.FromString,
          response_serializer=tracker__pb2.RelinquishControlResponse.SerializeToString,
      ),
      'move_panel': grpc.unary_unary_rpc_method_handler(
          servicer.move_panel,
          request_deserializer=tracker__pb2.MoveRequest.FromString,
          response_serializer=tracker__pb2.MoveResponse.SerializeToString,
      ),
      'stop': grpc.unary_unary_rpc_method_handler(
          servicer.stop,
          request_deserializer=tracker__pb2.StopRequest.FromString,
          response_serializer=tracker__pb2.StopResponse.SerializeToString,
      ),
      'stow': grpc.unary_unary_rpc_method_handler(
          servicer.stow,
          request_deserializer=tracker__pb2.StowRequest.FromString,
          response_serializer=tracker__pb2.StowResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'smartbox.TrackerController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
