# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import smartbox_resource_controller_pb2 as smartbox__resource__controller__pb2


class SmartBoxResourceControllerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get_tracker_status = channel.unary_unary(
        '/smartbox.SmartBoxResourceController/get_tracker_status',
        request_serializer=smartbox__resource__controller__pb2.TrackerSystemStatusRequest.SerializeToString,
        response_deserializer=smartbox__resource__controller__pb2.TrackerSystemStatusResponse.FromString,
        )
    self.request_control = channel.unary_unary(
        '/smartbox.SmartBoxResourceController/request_control',
        request_serializer=smartbox__resource__controller__pb2.RequestControlRequest.SerializeToString,
        response_deserializer=smartbox__resource__controller__pb2.RequestControlResponse.FromString,
        )
    self.relinquish_control = channel.unary_unary(
        '/smartbox.SmartBoxResourceController/relinquish_control',
        request_serializer=smartbox__resource__controller__pb2.RelinquishControlRequest.SerializeToString,
        response_deserializer=smartbox__resource__controller__pb2.RelinquishControlResponse.FromString,
        )
    self.move_panel = channel.unary_unary(
        '/smartbox.SmartBoxResourceController/move_panel',
        request_serializer=smartbox__resource__controller__pb2.MoveRequest.SerializeToString,
        response_deserializer=smartbox__resource__controller__pb2.MoveResponse.FromString,
        )
    self.stop = channel.unary_unary(
        '/smartbox.SmartBoxResourceController/stop',
        request_serializer=smartbox__resource__controller__pb2.StopRequest.SerializeToString,
        response_deserializer=smartbox__resource__controller__pb2.StopResponse.FromString,
        )
    self.stow = channel.unary_unary(
        '/smartbox.SmartBoxResourceController/stow',
        request_serializer=smartbox__resource__controller__pb2.StowRequest.SerializeToString,
        response_deserializer=smartbox__resource__controller__pb2.StowResponse.FromString,
        )
    self.set_light = channel.unary_unary(
        '/smartbox.SmartBoxResourceController/set_light',
        request_serializer=smartbox__resource__controller__pb2.LightRequest.SerializeToString,
        response_deserializer=smartbox__resource__controller__pb2.LightResponse.FromString,
        )
    self.weather_report = channel.unary_unary(
        '/smartbox.SmartBoxResourceController/weather_report',
        request_serializer=smartbox__resource__controller__pb2.WeatherRequest.SerializeToString,
        response_deserializer=smartbox__resource__controller__pb2.WeatherResponse.FromString,
        )
    self.panel_temperature = channel.unary_unary(
        '/smartbox.SmartBoxResourceController/panel_temperature',
        request_serializer=smartbox__resource__controller__pb2.PanelTemperatureRequest.SerializeToString,
        response_deserializer=smartbox__resource__controller__pb2.PanelTemperatureResponse.FromString,
        )


class SmartBoxResourceControllerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def get_tracker_status(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def request_control(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def relinquish_control(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def move_panel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def set_light(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def weather_report(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def panel_temperature(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SmartBoxResourceControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get_tracker_status': grpc.unary_unary_rpc_method_handler(
          servicer.get_tracker_status,
          request_deserializer=smartbox__resource__controller__pb2.TrackerSystemStatusRequest.FromString,
          response_serializer=smartbox__resource__controller__pb2.TrackerSystemStatusResponse.SerializeToString,
      ),
      'request_control': grpc.unary_unary_rpc_method_handler(
          servicer.request_control,
          request_deserializer=smartbox__resource__controller__pb2.RequestControlRequest.FromString,
          response_serializer=smartbox__resource__controller__pb2.RequestControlResponse.SerializeToString,
      ),
      'relinquish_control': grpc.unary_unary_rpc_method_handler(
          servicer.relinquish_control,
          request_deserializer=smartbox__resource__controller__pb2.RelinquishControlRequest.FromString,
          response_serializer=smartbox__resource__controller__pb2.RelinquishControlResponse.SerializeToString,
      ),
      'move_panel': grpc.unary_unary_rpc_method_handler(
          servicer.move_panel,
          request_deserializer=smartbox__resource__controller__pb2.MoveRequest.FromString,
          response_serializer=smartbox__resource__controller__pb2.MoveResponse.SerializeToString,
      ),
      'stop': grpc.unary_unary_rpc_method_handler(
          servicer.stop,
          request_deserializer=smartbox__resource__controller__pb2.StopRequest.FromString,
          response_serializer=smartbox__resource__controller__pb2.StopResponse.SerializeToString,
      ),
      'stow': grpc.unary_unary_rpc_method_handler(
          servicer.stow,
          request_deserializer=smartbox__resource__controller__pb2.StowRequest.FromString,
          response_serializer=smartbox__resource__controller__pb2.StowResponse.SerializeToString,
      ),
      'set_light': grpc.unary_unary_rpc_method_handler(
          servicer.set_light,
          request_deserializer=smartbox__resource__controller__pb2.LightRequest.FromString,
          response_serializer=smartbox__resource__controller__pb2.LightResponse.SerializeToString,
      ),
      'weather_report': grpc.unary_unary_rpc_method_handler(
          servicer.weather_report,
          request_deserializer=smartbox__resource__controller__pb2.WeatherRequest.FromString,
          response_serializer=smartbox__resource__controller__pb2.WeatherResponse.SerializeToString,
      ),
      'panel_temperature': grpc.unary_unary_rpc_method_handler(
          servicer.panel_temperature,
          request_deserializer=smartbox__resource__controller__pb2.PanelTemperatureRequest.FromString,
          response_serializer=smartbox__resource__controller__pb2.PanelTemperatureResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'smartbox.SmartBoxResourceController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
